symfony_cmf_routing_auto:
    auto_route_mapping:
        DTL\Bundle\VoyagerBundle\Document\Tour:
            content_path:
                routing_path:
                    provider:
                        name: specified
                        path: %symfony_cmf_routing_extra.route_basepath%
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: create
                namespace:
                    provider:
                        name: specified
                        path: tour
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: create
            content_name:
                provider:
                    name: content_method
                    method: getName
                exists_action:
                    strategy: auto_increment
                not_exists_action:
                    strategy: create
        DTL\Bundle\VoyagerBundle\Document\Stage:
            content_path:
                routing_path:
                    provider:
                        name: content_object
                        method: getTour
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: throw_exception
                prefix:
                    provider:
                        name: specified
                        path: stage
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: create
            content_name:
                provider:
                    name: content_method
                    method: getName
                exists_action:
                    strategy: auto_increment
                not_exists_action:
                    strategy: create
        DTL\Bundle\VoyagerBundle\Document\Journey:
            content_path:
                routing_path:
                    provider:
                        name: content_object
                        method: getStage
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: throw_exception
                prefix:
                    provider:
                        name: specified
                        path: journey
                    exists_action:
                        strategy: use
                    not_exists_action:
                        strategy: create
            content_name:
                provider:
                    name: content_method
                    method: getName
                exists_action:
                    strategy: auto_increment
                not_exists_action:
                    strategy: create
