imports:
    - { resource: config_dev.yml }

parameters:
    phpcr_workspace: standard_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false
