parameters:
  locale: en
  locales: [en, de]
  secret: 10784a86848b5412b5f7fa644e90ef24e
  database_driver: pdo_sqlite
  database_path: '%kernel.root_dir%/app.sqlite'
  phpcr_backend: 
      type: jackrabbit
      url: http://localhost:8080/server/
  phpcr_workspace: travel
  phpcr_user: admin
  phpcr_pass: admin
  database_host: null
  database_port: null
  database_name: null
  database_user: null
  database_password: null
